= Documentation as Code

== Treat documentation as code
* _Documentation as Code_ means your documentation process benefits from the same practices as your software development process. This includes version control, automated testing, and continuous integration. It also means that your documentation is written in a format that can be easily converted to other formats, such as HTML, PDF, and EPUB. 

* Some of these practices include
** Storing content in a version control system
** Separating content, configuration and presentation
** Leveraging automation for compilation, validation, verification and publishing
** Reusing shared materials (DRY)


== An example toolchain

* *Author*: Write, validate and preview your documentation content
** http://asciidoc.org/[AsciiDoc]
*** Plain text markup language for writing technical content
*** https://asciidoclive.com/edit/scratch/1[AsciiDoc Live Example]
* *Convert*: To the publication formats like HTML, DocBook, PDF, etc.
** https://asciidoctor.org/[Asciidoctor]
*** Processing AsciiDoc into a document model and converting it to output formats
* *Publish*
** Asciidoctor Maven / Gradle Plugins
*** Include in your CI/CD pipeline
** Antora
*** Multi-Repository documentation site generator for tech writers who writes in AsciiDoc
